import {writeFileSync} from "node:fs";
import {resolve} from "node:path";
import {run} from "../lib/exec.ts";
import type {Step} from "../lib/types.ts";

/**
 * Write skeleton fork.config.ts and the Flutter mirror. Most values are
 * placeholders the operator fills in via /admin/install. Only the values we
 * already know from CLI inputs (practice name, super-admin, agent names,
 * portal URL) get real values up front.
 */
export const forkConfigStep: Step = {
  id: "10-fork-config",
  title: "Write fork.config.ts skeleton",
  idempotent: true,
  async run({state, log}) {
    const {targetDir, projectId, practiceName, practiceShortName, superAdminEmail, portalDomain, adminAgentName, patientAgentName} =
      state.inputs;
    const apphostingUrl = state.artifacts.apphostingUrl;
    if (!targetDir || !projectId || !practiceName || !practiceShortName || !superAdminEmail || !adminAgentName || !patientAgentName) {
      throw new Error("inputs missing");
    }

    const portal = portalDomain ?? apphostingUrl?.replace(/^https?:\/\//, "") ?? `${projectId}.web.app`;
    const portalUrl = `https://${portal}`;

    const config = renderForkConfig({
      practiceName,
      practiceShortName,
      superAdminEmail,
      portalDomain: portal,
      portalUrl,
      adminAgentName,
      patientAgentName,
    });

    const target = resolve(targetDir, "fork.config.ts");
    writeFileSync(target, config);
    log.success(`Wrote skeleton ${target}`);

    // Mirror into mobile/lib/config/branding.dart — minimal subset.
    const dartPath = resolve(targetDir, "mobile", "lib", "config", "branding.dart");
    writeFileSync(dartPath, renderDartBranding({practiceName, practiceShortName, portalUrl}));
    log.success(`Wrote ${dartPath}`);

    // Also keep functions/src/_fork.config.ts in sync (the prebuild script
    // re-copies on `npm run build`, but we seed it now so deploy-first doesn't
    // need a separate prebuild round-trip).
    try {
      run("bash", [resolve(targetDir, "scripts", "sync-fork-config.sh")], {cwd: targetDir, capture: true});
      log.info("Synced fork.config.ts → functions/src/_fork.config.ts");
    } catch (err) {
      log.warn(`scripts/sync-fork-config.sh failed (will retry on functions build): ${(err as Error).message.split("\n")[0]}`);
    }
  },
};

interface ForkConfigVars {
  practiceName: string;
  practiceShortName: string;
  superAdminEmail: string;
  portalDomain: string;
  portalUrl: string;
  adminAgentName: string;
  patientAgentName: string;
}

function renderForkConfig(v: ForkConfigVars): string {
  // Generated by the installer. The ForkConfig interface lives in the
  // template; this file only emits the FORK_CONFIG export. Operators can
  // re-edit by hand or via /admin/install.
  return `/**
 * fork.config.ts — single source of truth for per-fork values.
 *
 * Generated by patient-installer. Edit fields directly OR re-open the
 * /admin/install wizard inside the deployed portal.
 */

export interface ForkConfig {
  readonly identity: {
    readonly appName: string;
    readonly practiceName: string;
    readonly shortName: string;
    readonly legalEntity: string;
    readonly smsSenderName: string;
  };
  readonly contact: {
    readonly supportEmail: string;
    readonly fromEmail: string;
    readonly supportPhone: string | null;
    readonly fax: string | null;
  };
  readonly urls: {
    readonly portalUrl: string;
    readonly domain: string;
    readonly additionalOrigins: readonly string[];
  };
  readonly address: {
    readonly street: string;
    readonly city: string;
    readonly state: string;
    readonly zip: string;
    readonly full: string;
    readonly mapsQuery: string;
  };
  readonly hours: readonly { readonly day: string; readonly time: string }[];
  readonly defaultAppointmentDuration: number;
  readonly practiceType: 'concierge' | 'standard';
  readonly logos: {
    readonly full: string;
    readonly fullDark: string;
    readonly icon: string;
    readonly alt: string;
  };
  readonly colors: {
    readonly primary: string;
    readonly secondary: string;
    readonly accent: string;
  };
  readonly agents: {
    readonly admin: { readonly name: string; readonly tagline: string; readonly pronouns: string };
    readonly patient: { readonly name: string; readonly tagline: string; readonly pronouns: string };
  };
  readonly platformVendor: {
    readonly name: string;
    readonly supportEmail: string;
    readonly billingDescriptor: string;
  };
  readonly superAdmin: {
    readonly email: string;
  };
  readonly limits: {
    readonly maxFieldChars: number;
  };
  readonly isDemo: boolean;
}

export const FORK_CONFIG: ForkConfig = {
  identity: {
    appName: ${json(v.practiceShortName)},
    practiceName: ${json(v.practiceName)},
    shortName: ${json(v.practiceShortName)},
    legalEntity: ${json(v.practiceName)},
    smsSenderName: ${json(v.practiceShortName)},
  },
  contact: {
    supportEmail: ${json(`support@${v.portalDomain}`)},
    fromEmail: ${json(`noreply@${v.portalDomain}`)},
    supportPhone: null,
    fax: null,
  },
  urls: {
    portalUrl: ${json(v.portalUrl)},
    domain: ${json(v.portalDomain)},
    additionalOrigins: [${json(v.portalUrl)}],
  },
  address: {
    street: 'TODO — set via /admin/install',
    city: '',
    state: '',
    zip: '',
    full: 'TODO — set via /admin/install',
    mapsQuery: '',
  },
  hours: [
    { day: 'Monday – Friday', time: '9:00 AM – 5:00 PM' },
    { day: 'Saturday – Sunday', time: 'Closed' },
  ],
  defaultAppointmentDuration: 20,
  practiceType: 'standard',
  logos: {
    full: '/branding/logo.png',
    fullDark: '/branding/logo.png',
    icon: '/branding/logo.png',
    alt: ${json(v.practiceShortName)},
  },
  colors: {
    primary: '#2563eb',
    secondary: '#475569',
    accent: '#0ea5e9',
  },
  agents: {
    admin: {
      name: ${json(v.adminAgentName)},
      tagline: 'Your practice management assistant',
      pronouns: 'they/them',
    },
    patient: {
      name: ${json(v.patientAgentName)},
      tagline: 'Here to help with your questions',
      pronouns: 'they/them',
    },
  },
  platformVendor: {
    name: 'Patient Portal Inc.',
    supportEmail: 'billing@patientportal.example',
    billingDescriptor: 'PATIENT PORTAL',
  },
  superAdmin: {
    email: ${json(v.superAdminEmail)},
  },
  limits: {
    maxFieldChars: 250,
  },
  isDemo: false,
};
`;
}

function renderDartBranding(v: {practiceName: string; practiceShortName: string; portalUrl: string}): string {
  return `// Generated by patient-installer. Mirror of /fork.config.ts (subset).
//
// Flutter cannot import TS so this file is regenerated by the installer
// AND can be re-emitted from /admin/install on the deployed portal.

class Branding {
  static const String appName = ${dart(v.practiceShortName)};
  static const String practiceName = ${dart(v.practiceName)};
  static const String shortName = ${dart(v.practiceShortName)};
  static const String portalUrl = ${dart(v.portalUrl)};
  static const String supportEmail = ${dart("support@" + v.portalUrl.replace(/^https?:\/\//, ""))};
}
`;
}

function json(s: string): string {
  return JSON.stringify(s);
}
function dart(s: string): string {
  return JSON.stringify(s);
}
